parameters:
#    photo_op.example.class: SDPHP\PhotoOpBundle\Example

services:
#    photo_op.example:
#        class: %photo_op.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
